services:
  parking-db:
    image: postgres:15
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - parking_data2:/var/lib/postgresql/data

volumes:
  parking_data2: