services:
  parking-db:
    image: postgres:15
    environment:
      POSTGRES_DB: parkingTicket2
      POSTGRES_USER: josimargonga
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - parking_data2:/var/lib/postgresql/data

volumes:
  parking_data2: